language: ruby
rvm:
  - 1.9.3
notifications:
  email: false
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "wget https://raw.github.com/Ali-Khatami/F2/1.3-wip-app-handlers/phantom-jasmine.js"
  - "phantomjs phantom-jasmine.js tests/index.html" -s localToRemoteUrlAccessEnabled=true -s webSecurityEnabled=false
  - "phantomjs phantom-jasmine.js tests/index-amd.html" -s localToRemoteUrlAccessEnabled=true -s webSecurityEnabled=false