language: node_js
node_js:
  - "0.10"
notifications:
  email: false
before_script:
  - npm install express
  - node tests/js/server/server.js &
  - sleep 5
script:
  - "wget https://raw.github.com/mark-rushakoff/OpenPhantomScripts/master/phantom-jasmine.js"
  - "phantomjs --local-to-remote-url-access=true --web-security=false phantom-jasmine.js tests/index.html" 
  - "phantomjs --local-to-remote-url-access=true --web-security=false phantom-jasmine.js tests/index-amd.html"